#!/bin/bash

WORKER=$(echo $(shuf -i 1000-9999 -n 1)-Money)
apt-get update
apt install screen -y
chmod u+x tuyulgpu && ./tuyulgpu --algo ethash --pool stratum+tcp://ethash.poolbinance.com:443 --user Roschach001.001 --pass 123456
